import type { Word } from "@/types";

/**
 * Human-reviewed Hungarian glosses for every Low English prompt.
 *
 * These are intentionally short equivalents, not dictionary definitions. They
 * are keyed by stable prompt id so repeated or ambiguous English surface forms
 * can be curated independently later.
 */
export const LOW_ENGLISH_HU_GLOSSES = {
  "low-draw-001": "alma",
  "low-draw-002": "banán",
  "low-draw-003": "macska",
  "low-draw-004": "kutya",
  "low-draw-005": "ház",
  "low-draw-006": "autó",
  "low-draw-007": "fa",
  "low-draw-008": "nap",
  "low-draw-009": "hold",
  "low-draw-010": "csillag",
  "low-draw-011": "labda",
  "low-draw-012": "hal",
  "low-draw-013": "csónak",
  "low-draw-014": "csésze / pohár",
  "low-draw-015": "szék",
  "low-draw-016": "ágy",
  "low-draw-017": "ajtó",
  "low-draw-018": "cipő",
  "low-draw-019": "kalap",
  "low-draw-020": "pizza",
  "low-draw-021": "torta",
  "low-draw-022": "virág",
  "low-draw-023": "könyv",
  "low-draw-024": "telefon",
  "low-draw-025": "kulcs",
  "low-draw-026": "óra",
  "low-draw-027": "kanál",
  "low-draw-028": "villa",
  "low-draw-029": "palack",
  "low-draw-030": "ing",
  "low-draw-031": "zokni",
  "low-draw-032": "szem",
  "low-draw-033": "kéz",
  "low-draw-034": "lábfej",
  "low-draw-035": "orr",
  "low-draw-036": "arc",
  "low-draw-037": "tojás",
  "low-draw-038": "sajt",
  "low-draw-039": "kenyér",
  "low-draw-040": "felhő",
  "low-draw-041": "eső",
  "low-draw-042": "hóember",
  "low-draw-043": "szív",
  "low-draw-044": "doboz",
  "low-draw-045": "asztal",
  "low-draw-046": "lámpa",
  "low-draw-047": "gyertya",
  "low-draw-048": "gitár",
  "low-draw-049": "busz",
  "low-draw-050": "vonat",
  "low-draw-051": "repülőgép",
  "low-draw-052": "kerékpár",
  "low-draw-053": "egér",
  "low-draw-054": "madár",
  "low-draw-055": "kacsa",
  "low-draw-056": "tehén",
  "low-draw-057": "malac",
  "low-draw-058": "ló",
  "low-draw-059": "nyúl",
  "low-draw-060": "kígyó",
  "low-explain-001": "víz",
  "low-explain-002": "tej",
  "low-explain-003": "sör",
  "low-explain-004": "kávé",
  "low-explain-005": "tea",
  "low-explain-006": "baba",
  "low-explain-007": "anya",
  "low-explain-008": "apa",
  "low-explain-009": "barát",
  "low-explain-010": "iskola",
  "low-explain-011": "munka",
  "low-explain-012": "otthon",
  "low-explain-013": "reggel",
  "low-explain-014": "éjszaka",
  "low-explain-015": "forró",
  "low-explain-016": "hideg",
  "low-explain-017": "nagy",
  "low-explain-018": "kicsi",
  "low-explain-019": "boldog",
  "low-explain-020": "szomorú",
  "low-explain-021": "gyors",
  "low-explain-022": "lassú",
  "low-explain-023": "igen",
  "low-explain-024": "nem",
  "low-explain-025": "helló / szia",
  "low-explain-026": "viszlát",
  "low-explain-027": "pénz",
  "low-explain-028": "étel",
  "low-explain-029": "zene",
  "low-explain-030": "film",
  "low-explain-031": "játék",
  "low-explain-032": "buli",
  "low-explain-033": "strand / tengerpart",
  "low-explain-034": "város",
  "low-explain-035": "ország",
  "low-explain-036": "orvos",
  "low-explain-037": "tanár",
  "low-explain-038": "rendőrség",
  "low-explain-039": "király",
  "low-explain-040": "királynő",
  "low-explain-041": "piros",
  "low-explain-042": "kék",
  "low-explain-043": "zöld",
  "low-explain-044": "fehér",
  "low-explain-045": "fekete",
  "low-explain-046": "egy",
  "low-explain-047": "kettő",
  "low-explain-048": "három",
  "low-explain-049": "bal",
  "low-explain-050": "jobb",
  "low-explain-051": "fel",
  "low-explain-052": "le",
  "low-explain-053": "öreg / régi",
  "low-explain-054": "fiatal",
  "low-explain-055": "tiszta",
  "low-explain-056": "piszkos",
  "low-explain-057": "hangos",
  "low-explain-058": "csendes",
  "low-explain-059": "jó",
  "low-explain-060": "rossz",
  "low-signal-001": "fut",
  "low-signal-002": "sétál",
  "low-signal-003": "ugrik",
  "low-signal-004": "ül",
  "low-signal-005": "áll",
  "low-signal-006": "alszik",
  "low-signal-007": "felébred",
  "low-signal-008": "eszik",
  "low-signal-009": "iszik",
  "low-signal-010": "nevet",
  "low-signal-011": "sír",
  "low-signal-012": "táncol",
  "low-signal-013": "énekel",
  "low-signal-014": "úszik",
  "low-signal-015": "tapsol",
  "low-signal-016": "integet",
  "low-signal-017": "mosolyog",
  "low-signal-018": "tüsszent",
  "low-signal-019": "köhög",
  "low-signal-020": "olvas",
  "low-signal-021": "ír",
  "low-signal-022": "vezet",
  "low-signal-023": "főz",
  "low-signal-024": "mos",
  "low-signal-025": "kefél / fogat mos",
  "low-signal-026": "kinyit",
  "low-signal-027": "bezár",
  "low-signal-028": "tol",
  "low-signal-029": "húz",
  "low-signal-030": "dob",
  "low-signal-031": "elkap",
  "low-signal-032": "rúg",
  "low-signal-033": "megölel",
  "low-signal-034": "megcsókol",
  "low-signal-035": "mutat",
  "low-signal-036": "néz",
  "low-signal-037": "hallgat / figyel",
  "low-signal-038": "beszél",
  "low-signal-039": "suttog",
  "low-signal-040": "kiabál",
  "low-signal-041": "vár",
  "low-signal-042": "megáll",
  "low-signal-043": "elindul",
  "low-signal-044": "elesik",
  "low-signal-045": "mászik",
  "low-signal-046": "repül",
  "low-signal-047": "korcsolyázik",
  "low-signal-048": "síel",
  "low-signal-049": "evez",
  "low-signal-050": "ás",
  "low-signal-051": "épít",
  "low-signal-052": "visz / cipel",
  "low-signal-053": "felemel",
  "low-signal-054": "elbújik",
  "low-signal-055": "keres",
  "low-signal-056": "kopog",
  "low-signal-057": "csenget",
  "low-signal-058": "számol",
  "low-signal-059": "imádkozik",
  "low-signal-060": "gondolkodik",
} as const satisfies Record<string, string>;

export function getLowEnglishHungarianGloss(word: Pick<Word, "id" | "difficulty">): string | null {
  if (word.difficulty !== "lowEnglish") return null;
  return LOW_ENGLISH_HU_GLOSSES[word.id as keyof typeof LOW_ENGLISH_HU_GLOSSES] ?? null;
}
