import type { RegisteredTaskContentSource } from "@/types/packs";

export const taskContentSources = [
  {
    id: "word-pack-hu",
    kind: "existing-word-pack",
    location: "src/data/words-hu.json",
    locale: "hu",
    categories: ["draw", "explain", "signal"],
    difficulties: ["easy", "medium", "hard"],
  },
  {
    id: "word-pack-en",
    kind: "existing-word-pack",
    location: "src/data/words-en.json",
    locale: "en",
    categories: ["draw", "explain", "signal"],
    difficulties: ["lowEnglish", "easy", "medium", "challenging", "hard"],
  },
  {
    id: "movies-pack-hu",
    kind: "pack-data",
    location: "src/data/movies-hu.json",
    locale: "hu",
    categories: ["draw", "explain", "signal"],
    difficulties: ["easy", "medium"],
  },
  {
    id: "movies-pack-en",
    kind: "pack-data",
    location: "src/data/movies-en.json",
    locale: "en",
    categories: ["draw", "explain", "signal"],
    difficulties: ["easy", "medium"],
  },
  {
    id: "series-pack-hu",
    kind: "pack-data",
    location: "src/data/series-hu.json",
    locale: "hu",
    categories: ["draw", "explain", "signal"],
    difficulties: ["easy", "medium"],
  },
  {
    id: "series-pack-en",
    kind: "pack-data",
    location: "src/data/series-en.json",
    locale: "en",
    categories: ["draw", "explain", "signal"],
    difficulties: ["easy", "medium"],
  },
  {
    id: "gaming-pack-hu",
    kind: "pack-data",
    location: "src/data/gaming-hu.json",
    locale: "hu",
    categories: ["draw", "explain", "signal"],
    difficulties: ["easy", "medium"],
  },
  {
    id: "gaming-pack-en",
    kind: "pack-data",
    location: "src/data/gaming-en.json",
    locale: "en",
    categories: ["draw", "explain", "signal"],
    difficulties: ["easy", "medium"],
  },
] as const satisfies readonly RegisteredTaskContentSource[];
